### PR TITLE
Add DenverFP's Haskell Book Club

### PR DESCRIPTION
**Pull request by parsonsmatt**
:smile:

### CODE REVIEW

**Comment by sjsyrek** [comment]
Hey Matt! Of course I want to merge this! But are you using these guidelines for your group, or do you just want to be on the list? Or both? I'm asking people to fork the repo and link to that, not a Meetup page, per se. But if this is what you prefer, I will click the green button. Also, thanks for the links (by way of learnhaskell) to the Recurse Center's social rules and Chris Done's blog post. I added links to both.

**Comment by parsonsmatt** [comment]
Great question -- @DebugSteven is the one actually running the book club. I believe they are using these guidelines but I'll let them chime in.

**Comment by DebugSteven** [comment]
There are a couple of differences in our group. We don't have study partners, don't explicitly rule out people coming and going from the group, and we are only doing one chapter a week. If Denver FP does another book club after this one, I would definitely follow these guidelines exactly. I would like to link, but if not now I anticipate another book club will start up in late January/February.

**Comment by sjsyrek** [comment]
@DebugSteven You don't need to follow the guidelines exactly, just the spirit of them, more or less. I mean, they're only a recommendation. The schedule, in particular, is completely optional. I will make that clearer in the text.

Anyway, I will go ahead and merge your pull request. If you want to actually fork the repo, you can do another pr to link to that instead—if it's useful to you. Likewise if you want to link back to it. In the meantime, my primary goal is to spread the study group gospel, so we're all good here. I just wasn't sure what _you_ needed. ❤️

**Comment by sjsyrek** [comment]
Further notes: study partners are an idea I'm trying out, but I realize not everyone will want to make time for it. Letting people come and go is your call, but you may become frustrated if people expect you to catch them up. Or, conversely, show up with zero Haskell experience demanding to know what a monad is. Most of my guidelines are designed to protect the sanity of the organizer, so YMMV. One chapter a week is great if you have the time. That's what I did the first go around. You might want to build in a stopping point (i.e. chapter 18) if you don't especially want to commit to a 31 week study group. Thanks for doing this!

**Pull request merged**
