### PR TITLE
Add Kyiv Study Group

### PR DESCRIPTION
**Pull request by k-bx**
Thank you very much for the project. I liked it so much that I was inspired to make my own study group in Kyiv!

### CODE REVIEW

**Comment by bitemyapp** [comment]
Hi @k-bx!

**Comment by sjsyrek** [comment]
Awesome! I'd love to visit someday. Not so far from Berlin.

**Comment by k-bx** [comment]
Hi @bitemyapp ✋️ Please see inbox for me asking for discounts 😀

@sjayrek you are very welcome to visit! We also have kievfprog events from time to time for talks format, I'm sure the group will be interested to visit those as well.

**Comment by bitemyapp** [comment]
@k-bx I'll give 'er a look tonight after work!

**Comment by sjsyrek** [comment]
@k-bx I do have a talk on FP basics I can deliver

**Comment by sjsyrek** [comment]
@k-bx Did you personally translate this whole repo?

**Comment by k-bx** [comment]
Thanks, Chris!

@sjsyrek  yes, but only guide.md. Took less than 2 hours I think.

Regarding the talk — wonderful! Ping me in advance and let's discuss the best date to schedule things with @darkproger , who is our main organizer :)

**Pull request merged**
