### PR TITLE
added german translation of guidelines.md

### PR DESCRIPTION
**Pull request by typetetris**
there still is plenty to improve, consider it as a starting point for further refinements. Some wording will be odd and a few translation are a bit loose, but I tried my best :)

### CODE REVIEW

**Review by sjsyrek — COMMENTED** [review]
This is great, and I'm hardly one to quibble over a translation I could only hope to partly read at this point. Are there really German words for things like Functor and Monad??

**Comment by typetetris** [comment]
For Functor and Monad yes, but I struggled with Applicative. Maybe I need to ask one of my former teachers at university about it.
But maybe its pointless to translate those.

**Review by sjsyrek — COMMENTED** [review]
Yeah, I think maybe it's not worth translating these terms… but what do you think?

**Comment by typetetris** [comment]
One could argue, that you must not translate them, as the english terms are part of the haskell terminology and are names in their own regard.

Otherwise, If you translate them, you can lure people in, who are not that well versed with english.

All in all it is not much of a big deal, whether you write `functor` or `Funktor` so maybe we spend already to much time thinking about it.

**Comment by sjsyrek** [comment]
Indeed. I didn't mean to belabor the point. As long as nobody is confused. Thanks for working on this. And you're doing the group in Karlsruhe, I assume? Please add it to my list!

**Pull request merged**
